build both

diff --git a/build-repo b/build-repo
--- a/build-repo
+++ b/build-repo
@@ -31,13 +31,6 @@ parser.add_argument('--force', action='store_true')
 parser.add_argument('--global-menu', action='store_true')
 args = parser.parse_args()
 
-if args.global_menu:
-  ARCHS = ['amd64']
-  RELEASE_REPO = 'global-menu'
-else:
-  ARCHS = ['i386', 'amd64']
-  #RELEASE_REPO = 'apt-get'
-  RELEASE_REPO = 'test'
 PACKAGES = ['zotero', 'jurism']
 MAINTAINER = 'emiliano.heyns@iris-advies.com'
 GPGKEY = 'dpkg'
@@ -54,7 +47,7 @@ def rm_rf(*paths):
     if os.path.isfile(path): os.remove(path)
 
 class Package:
-  def __init__(self, repo, binary_url, package, assets, name):
+  def __init__(self, repo, binary_url, package, assets, name, dependencies, global_menu):
     # find current version
     feed = f'https://github.com/{repo}/releases.atom'
     response = urlopen(feed).read()
@@ -62,10 +55,12 @@ class Package:
     root = ET.fromstring(response)
     version = root.find('{http://www.w3.org/2005/Atom}entry/{http://www.w3.org/2005/Atom}id').text
     self.version = version.split('/')[-1]
-    
+
     self.binary_url = binary_url
     self.package = package
     self.name = name
+    self.dependencies = dependencies
+    self.global_menu = global_menu
 
     self.public = Munch.fromDict({arch: None for arch in ARCHS})
 
@@ -128,7 +123,7 @@ class Package:
       tar.extract(member, f'build/usr/lib/{self.package}')
     tar.close()
 
-    self.global_menu(f'build/usr/lib/{self.package}')
+    self.patch_global_menu(f'build/usr/lib/{self.package}')
 
     with open(f'build/usr/lib/{self.package}/distribution/policies.json', 'w') as f:
       f.write(json.dumps({ "policies": { "DisableAppUpdate": True } }))
@@ -136,7 +131,7 @@ class Package:
     desktop = configparser.RawConfigParser()
     desktop.add_section('Desktop Entry')
     desktop.set('Desktop Entry', 'Name', self.name)
-    if args.global_menu:
+    if self.global_menu:
       desktop.set('Desktop Entry', 'Comment', 'Open-source reference manager (global menu support)')
     else:
       desktop.set('Desktop Entry', 'Comment', 'Open-source reference manager')
@@ -147,7 +142,7 @@ class Package:
     desktop.set('Desktop Entry', 'MimeType', ';'.join([
       'x-scheme-handler/zotero',
 
-      # Research Information Systems Document 
+      # Research Information Systems Document
       'ris',
       'application/x-research-info-systems',
       'application/x-endnote-refer',
@@ -164,22 +159,22 @@ class Package:
       'mods',
       'application/mods+xml',
 
-      # Resource Description Framework Document 
+      # Resource Description Framework Document
       'rdf',
       'application/rdf+xml',
 
-      # BibTeX Document 
+      # BibTeX Document
       'bib',
       'bibtex',
       'application/x-bibtex',
       'text/x-bibtex',
 
-      # MARC Record 
+      # MARC Record
       'mrc',
       'marc',
       'application/marc',
 
-      # CSL Citation Style 
+      # CSL Citation Style
       'csl',
       'vnd.citationstyles.style+xml',
     ]))
@@ -190,7 +185,7 @@ class Package:
     with open('build/DEBIAN/control', 'w') as f:
       print(f'Package: {self.package}', file=f)
       print(f'Architecture: {arch}', file=f)
-      print('Depends: libnss3-dev', file=f)
+      print(f'Depends: libnss3-dev {self.dependencies}'.strip(), file=f)
       print(f'Maintainer: {MAINTAINER}', file=f)
       print('Section: Science', file=f)
       print('Priority: optional', file=f)
@@ -200,8 +195,9 @@ class Package:
     run(f'dpkg-deb --root-owner-group --build -Zgzip build repo/{deb}')
     run(f'dpkg-sig -k {GPGKEY} --sign builder repo/{deb}')
 
-  def global_menu(self, installdir):
-    if not args.global_menu: return
+  def patch_global_menu(self, installdir):
+    if not self.global_menu: return
+    print('  patching for global menu')
 
     url = urlopen('https://github.com/ripefig/Firefox-ESR-52-Global-Menu/releases/latest').geturl().replace('/tag/', '/download/') + '/libxul.so'
     urlretrieve(url, f'{installdir}/libxul.so')
@@ -231,78 +227,93 @@ class Package:
 # let's get it started
 gh = login(token=os.getenv('GITHUB_TOKEN'))
 repo = repo = gh.repository('retorquere', 'zotero-deb')
-release = repo.release_from_tag(RELEASE_REPO)
-assets = release.assets()
 
-packages = Munch(
-  zotero = Package(
-    repo='zotero/zotero',
-    package='zotero',
-    name='Zotero',
-    binary_url='https://www.zotero.org/download/client/dl?channel=release&platform=linux-{arch}&version={version}',
-    assets=[asset.name for asset in assets]
-  ),
-  jurism = Package(
-    repo='Juris-M/zotero',
-    package='jurism',
-    name='Juris-M',
-    binary_url='https://github.com/Juris-M/assets/releases/download/client%2Frelease%2F{version}/Jurism-{version}_linux-{arch}.tar.bz2',
-    assets=[asset.name for asset in assets]
-  )
-)
+for global_menu in [False, True]:
+  if global_menu:
+    ARCHS = ['amd64']
+    RELEASE_REPO = 'global-menu'
+  else:
+    ARCHS = ['i386', 'amd64']
+    #RELEASE_REPO = 'apt-get'
+    RELEASE_REPO = 'test'
+  print(f'Building {RELEASE_REPO}')
 
-if not packages.zotero.needs_update and not packages.jurism.needs_update:
-  print('nothing to do')
-  sys.exit(0)
+  release = repo.release_from_tag(RELEASE_REPO)
+  assets = release.assets()
 
-rm_rf('repo')
-os.mkdir('repo')
-
-for asset in assets:
-  asset.delete()
-#  if asset.name.startswith('zotero') and packages.zotero.needs_update:
-#    #asset.delete()
-#    continue
-#  if asset.name.startswith('jurism') and packages.jurism.needs_update:
-#    #asset.delete()
-#    continue
-#  print(f'Downloading {asset.name}')
-#  with open(os.path.join('repo', asset.name), 'wb') as f:
-#    asset.download(f)
-
-for package in PACKAGES:
-  for arch in ARCHS:
-    packages[package].build(arch)
-
-run(f'gpg --armor --export {GPGKEY} > repo/deb.gpg.key')
-run(f'cd repo && apt-ftparchive packages . > Packages')
-run(f'bzip2 -kf repo/Packages')
-run(f'cd repo && apt-ftparchive release . > Release')
-run(f'gpg --yes -abs -u {GPGKEY} -o repo/Release.gpg --digest-algo sha256 repo/Release')
-run(f'gpg --yes -abs -u {GPGKEY} --clearsign -o repo/InRelease --digest-algo sha256 repo/Release')
-
-with open('repo/install.sh', 'w') as f:
-  print(textwrap.dedent(f'''
-    if [ -x "$(command -v curl)" ]; then
-      curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/deb.gpg.key | sudo apt-key add -
-    elif [ -x "$(command -v wget)" ]; then
-      wget -qO- https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/deb.gpg.key | sudo apt-key add -
-    else
-      echo "Error: need wget or curl installed." >&2
-      exit 1
-    fi
-
-    cat << EOF | sudo tee /etc/apt/sources.list.d/zotero.list
-    deb https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/ ./
-    EOF
-  '''), file=f)
-
-for asset in sorted(glob.glob('repo/*')):
-  content_type = mimetypes.guess_type(asset)[0] or 'application/octet-stream'
-  print(f'  Uploading {asset} ({content_type})')
-  with open(asset, 'rb') as f:
-    release.upload_asset(
-      asset=f,
-      name=os.path.basename(asset),
-      content_type=content_type
+  packages = Munch(
+    zotero = Package(
+      repo='zotero/zotero',
+      package='zotero',
+      name='Zotero',
+      binary_url='https://www.zotero.org/download/client/dl?channel=release&platform=linux-{arch}&version={version}',
+      assets=[asset.name for asset in assets],
+      dependencies='',
+      global_menu=global_menu
+    ),
+    jurism = Package(
+      repo='Juris-M/zotero',
+      package='jurism',
+      name='Juris-M',
+      binary_url='https://github.com/Juris-M/assets/releases/download/client%2Frelease%2F{version}/Jurism-{version}_linux-{arch}.tar.bz2',
+      assets=[asset.name for asset in assets],
+      dependencies='default-jre libreoffice-java-common',
+      global_menu=global_menu
     )
+  )
+
+  if not packages.zotero.needs_update and not packages.jurism.needs_update:
+    print('nothing to do')
+    break
+
+  rm_rf('repo')
+  os.mkdir('repo')
+
+  for asset in assets:
+    asset.delete()
+  #  if asset.name.startswith('zotero') and packages.zotero.needs_update:
+  #    #asset.delete()
+  #    continue
+  #  if asset.name.startswith('jurism') and packages.jurism.needs_update:
+  #    #asset.delete()
+  #    continue
+  #  print(f'Downloading {asset.name}')
+  #  with open(os.path.join('repo', asset.name), 'wb') as f:
+  #    asset.download(f)
+
+  for package in PACKAGES:
+    for arch in ARCHS:
+      packages[package].build(arch)
+
+  run(f'gpg --armor --export {GPGKEY} > repo/deb.gpg.key')
+  run(f'cd repo && apt-ftparchive packages . > Packages')
+  run(f'bzip2 -kf repo/Packages')
+  run(f'cd repo && apt-ftparchive release . > Release')
+  run(f'gpg --yes -abs -u {GPGKEY} -o repo/Release.gpg --digest-algo sha256 repo/Release')
+  run(f'gpg --yes -abs -u {GPGKEY} --clearsign -o repo/InRelease --digest-algo sha256 repo/Release')
+
+  with open('repo/install.sh', 'w') as f:
+    print(textwrap.dedent(f'''
+      if [ -x "$(command -v curl)" ]; then
+        curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/deb.gpg.key | sudo apt-key add -
+      elif [ -x "$(command -v wget)" ]; then
+        wget -qO- https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/deb.gpg.key | sudo apt-key add -
+      else
+        echo "Error: need wget or curl installed." >&2
+        exit 1
+      fi
+
+      cat << EOF | sudo tee /etc/apt/sources.list.d/zotero.list
+      deb https://github.com/retorquere/zotero-deb/releases/download/{RELEASE_REPO}/ ./
+      EOF
+    '''), file=f)
+
+  for asset in sorted(glob.glob('repo/*')):
+    content_type = mimetypes.guess_type(asset)[0] or 'application/octet-stream'
+    print(f'  Uploading {asset} ({content_type})')
+    with open(asset, 'rb') as f:
+      release.upload_asset(
+        asset=f,
+        name=os.path.basename(asset),
+        content_type=content_type
+      )
